const API='/api/v1/public/';
const $=s=>document.querySelector(s);
const text=v=>String(v??'');
const rub=new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0});
let catalog=null;
function el(tag,content=''){const n=document.createElement(tag);n.textContent=content;return n}
async function loadCatalog(){try{const r=await fetch(API+'catalog');if(!r.ok)throw Error();catalog=await r.json();const data=catalog.data||catalog;const services=(data.services||[]).filter(x=>x.active!==false);const options=(data.options||data.service_options||services.flatMap(x=>(x.options||[]).map(o=>({...o,service_title:x.title})))).filter(x=>x.active!==false);const list=$('#catalog-list');list.replaceChildren();options.forEach(o=>{const s=el('article');s.append(el('h3',o.service_title?`${o.service_title}: ${o.title||o.name||'Вариант'}`:o.title||o.name||'Услуга'));s.append(el('p',o.duration_minutes?`${o.duration_minutes} минут`:o.duration||'Длительность уточняется'));const p=el('p',o.price_minor==null||o.pricing_mode==='NEGOTIATED'?'По договорённости':rub.format(o.price_minor/100));p.className='price';s.append(p);list.append(s)});if(!options.length)$('#catalog-status').textContent='Подходящие варианты сейчас недоступны.';else{$('#catalog-status').textContent='';const sel=$('#service-option');sel.replaceChildren(el('option','Выберите вариант'));options.forEach(o=>{const x=el('option',o.title||o.name||'Вариант');x.value=o.id;sel.append(x)})}if(data.location_link){const a=el('a','Открыть ссылку на расположение');a.href=data.location_link;a.rel='noopener';$('#conditions-title').after(a)}if(services.length===0)$('#catalog-status').textContent='Каталог временно недоступен.'}catch{$('#catalog-status').textContent='Не удалось загрузить каталог. Попробуйте обновить страницу позже.'}}
function acquisition(){const q=new URLSearchParams(location.search),a={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(k=>{if(q.get(k))a[k]=q.get(k).slice(0,200)});return a}
function key(){let k=sessionStorage.getItem('inquiry-key');if(!k){k=crypto.randomUUID();sessionStorage.setItem('inquiry-key',k)}return k}
async function submit(e){e.preventDefault();const f=new FormData(e.target),status=$('#form-status');if(!e.target.reportValidity())return;status.className='';status.textContent='Отправляем…';let token=sessionStorage.getItem('submission-token');try{if(!token){const tr=await fetch(API+'submission-tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!tr.ok)throw Error();token=(await tr.json()).submission_token;sessionStorage.setItem('submission-token',token)}const body={submission_token:token,catalog_version:catalog?.catalog_version??catalog?.version,service_option_id:f.get('service_option_id'),requester:{name:f.get('name'),contact:{kind:f.get('contact_kind'),value:f.get('contact_value')}},participants_count:Number(f.get('participants_count')),requested_time:{date:f.get('date'),time_text:f.get('time_text')},experience:f.get('experience'),comment:f.get('comment'),acquisition:acquisition()};const r=await fetch(API+'inquiries',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key()},body:JSON.stringify(body)});if(!r.ok)throw Error();status.className='success';status.textContent='Заявка принята. Это не подтверждение бронирования: владелец свяжется с вами для согласования.';sessionStorage.removeItem('inquiry-key');sessionStorage.removeItem('submission-token')}catch{status.className='error';status.textContent='Не удалось подтвердить отправку. Проверьте связь и повторите попытку — данные и ключ сохранены.'}}
loadCatalog();$('#inquiry-form').addEventListener('submit',submit);
