const API='/api/v1/public/';
const $=s=>document.querySelector(s);
const text=v=>String(v??'');
const rub=new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0});
let catalog=null;
function el(tag,content=''){const n=document.createElement(tag);n.textContent=content;return n}
function apiData(payload){return payload&&payload.data&&typeof payload.data==='object'?payload.data:payload}
async function loadCatalog(){try{const r=await fetch(API+'catalog');if(!r.ok)throw Error();catalog=apiData(await r.json());const services=(catalog.services||[]).filter(x=>x.active!==false);const options=services.flatMap(service=>(service.options||[]).filter(o=>o.active!==false).map(o=>({...o,service_title:service.title,service_description:service.description,service_information:service.information})));const list=$('#catalog-list');list.replaceChildren();options.forEach(o=>{const card=el('article');card.append(el('h3',`${o.service_title||'Услуга'} — ${o.title||o.name||'Вариант'}`));if(o.service_description)card.append(el('p',o.service_description));card.append(el('p',o.duration_minutes==null?'Длительность согласуется':`${o.duration_minutes} минут`));const price=el('p',o.price_minor==null||o.pricing_mode==='NEGOTIATED'?'По договорённости':rub.format(o.price_minor/100));price.className='price';card.append(price);list.append(card)});if(!options.length){$('#catalog-status').textContent='Подходящие варианты сейчас недоступны.';return}$('#catalog-status').textContent='';const sel=$('#service-option');sel.replaceChildren(el('option','Выберите вариант'));options.forEach(o=>{const x=el('option',`${o.service_title||'Услуга'} — ${o.title||o.name||'Вариант'}`);x.value=o.id;sel.append(x)});const rules=catalog.visit_rules;if(rules){const rulesBox=$('#visit-rules');const item=el('article');item.append(el('h3','Правила визита'));item.append(el('p',Array.isArray(rules)?rules.join(' '):String(rules)));rulesBox.append(item)}if(catalog.location_link){const a=el('a','Открыть расположение');a.href=catalog.location_link;a.rel='noopener noreferrer';a.target='_blank';$('#location').append(a)}}catch{$('#catalog-status').textContent='Не удалось загрузить каталог. Попробуйте обновить страницу позже.'}}
function acquisition(){const q=new URLSearchParams(location.search),a={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(k=>{if(q.get(k))a[k]=q.get(k).slice(0,200)});return a}
function key(){let k=sessionStorage.getItem('inquiry-key');if(!k){k=crypto.randomUUID();sessionStorage.setItem('inquiry-key',k)}return k}
async function submit(e){e.preventDefault();const f=new FormData(e.target),status=$('#form-status');if(!e.target.reportValidity())return;status.className='';status.textContent='Отправляем…';let token=sessionStorage.getItem('submission-token');const idempotencyKey=key();try{if(!token){const tr=await fetch(API+'submission-tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!tr.ok)throw Error();token=apiData(await tr.json()).submission_token;if(!token)throw Error();sessionStorage.setItem('submission-token',token)}const body={submission_token:token,catalog_version:catalog?.catalog_version,service_option_id:f.get('service_option_id'),requester:{name:f.get('name'),contact:{kind:f.get('contact_kind'),value:f.get('contact_value')}},participants_count:Number(f.get('participants_count')),requested_time:{date:f.get('date'),time_text:f.get('time_text')},experience:f.get('experience'),comment:f.get('comment'),acquisition:acquisition()};const r=await fetch(API+'inquiries',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey},body:JSON.stringify(body)});if(!r.ok)throw Error();const receipt=apiData(await r.json());if(receipt.received===false)throw Error();status.className='success';status.textContent='Заявка принята. Это не подтверждение бронирования: владелец свяжется с вами для согласования.';sessionStorage.removeItem('inquiry-key');sessionStorage.removeItem('submission-token')}catch{status.className='error';status.textContent='Не удалось подтвердить отправку. Проверьте связь и повторите попытку — данные и ключ сохранены.'}}
loadCatalog();$('#inquiry-form').addEventListener('submit',submit);
